services:

  mailserver:
    build: mailserver/
    depends_on:
      - mongodb
      - postfix
    ports:
      - "25:25"
    networks:
      - database
      - postfix

  website:
    build: website/
    depends_on:
      - mongodb
      - postfix
    ports:
      - "8080:8080"
    networks:
      - database
      - postfix

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    networks:
      - database
    command: mongod

  postfix:
    build: environment/postfix/
    networks:
      - postfix

volumes:

  mailserver_config:
  website_config:

  mongodb:
  mongodb_config:

networks:
  database:
  postfix:
