services:

  mailserver:
    image: bluefireoly/spamgourmet:mailserver
    depends_on:
      - mongodb
      - postfix
    ports:
      - "25:25"
    volumes:
      - ./configs:/app/config
    links:
      - mongodb
    networks:
      - mongodb
      - postfix

  website:
    image: bluefireoly/spamgourmet:website
    depends_on:
      - mongodb
      - postfix
    ports:
      - "8080:8080"
    volumes:
      - ./configs:/app/config
    networks:
      - mongodb
      - postfix

  mongodb:
    image: mongo:4
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - mongodb

  postfix:
    image: bluefireoly/spamgourmet:postfix
    networks:
      - postfix

volumes:
  mongodb_data:
  mongodb_config:

networks:
  postfix:
  mongodb:
