services:

  mailserver:
    image: bluefireoly/spamgourmet:mailserver
    depends_on:
      - mongodb
      - postfix
    ports:
      - "25:25"
    volumes:
      - mailserver_config:/config
    networks:
      - database
      - postfix

  website:
    image: bluefireoly/spamgourmet:website
    depends_on:
      - mongodb
      - postfix
    ports:
      - "8080:8080"
    volumes:
      - website_config:/config
    networks:
      - database
      - postfix

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    networks:
      - database
    command: mongod

  postfix:
    image: bluefireoly/spamgourmet:postfix
    networks:
      - postfix

volumes:

  mailserver_config:
  website_config:

  mongodb:
  mongodb_config:

networks:
  database:
  postfix:
